trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  inputs:
    script: |
      python -m venv .venv
      source .venv/bin/activate

- task: CmdLine@2
  inputs:
    script: 'pip install -r requirements.txt'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Visual Studio Enterprise Subscription(313553f9-7426-4f0c-957b-47085446356c)'
    appType: 'functionAppLinux'
    appName: 'cca5-cin-ufpe-br'
    deployToSlotOrASE: true
    resourceGroupName: 'test-resource-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.9'
    deploymentMethod: 'auto'